address = Address();
address.setStreet(street);
address.setCountry(country);
address.setStateOrProvince(state);
address.setCity(city);
address.setCity(city);
address.setHouseNumberOrName(number);
address.setPostalCode(postalCode);
address.setPostalCode(postalCode);
address.setPostalCode(postalCode);
